// Uses the real local server, Git history, and renderer; no filesystem writes.
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(resolve(process.argv[2],'package.json'));
const {JSDOM}=require('jsdom');
const origin='http://127.0.0.1:4187/';
const dom=new JSDOM(readFileSync(new URL('../jsonantt/web/index.html',import.meta.url),'utf8'),{url:origin,pretendToBeVisual:true});
for(const key of ['window','document','localStorage','HTMLElement','HTMLLabelElement','navigator','DOMParser']) Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
dom.window.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
dom.window.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new window.Event('close'));};
const nativeFetch=globalThis.fetch;
globalThis.fetch=(url,options)=>nativeFetch(new URL(url,origin),options);
const q=selector=>document.querySelector(selector);
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(check,message) {for(let i=0;i<1500;i++){if(check())return;await pause(10);} assert.fail(message+': '+q('#status').textContent);}
const {state}=await import('../jsonantt/web/app.mjs');
await until(()=>state.chart,'Boot');
assert.equal(q('[data-canvas-tab="compare-gantt"]'),null);
const unsavedBeforeHistory=state.source;
q('#open-compare').click();
assert.equal(q('#compare-history').disabled,false);
q('#compare-history').click();
assert(q('#local-file-dialog').open,'History with no path should offer a file picker');
await until(()=>q('#local-file-list button'),'History file listing');
q('#local-file-path').value=resolve('examples');q('#local-file-browse').click();
await until(()=>[...q('#local-file-list').children].some(button=>button.title===resolve('examples/simple.json')),'Browse JSON directory');
const fileButton=[...q('#local-file-list').children].find(button=>button.title===resolve('examples/simple.json'));
fileButton.click();
assert.equal(fileButton.getAttribute('aria-pressed'),'true');
assert.equal(q('#local-file-path').value,resolve('examples/simple.json'));
assert.equal(q('#local-file-open').textContent,'Use this file');
q('#local-file-open').click();
await until(()=>q('#compare-revisions').options.length,'History after locating current file');
assert.equal(state.source,unsavedBeforeHistory,'Locating history must preserve the unsaved editor');
assert(q('#compare-current-file').textContent.includes(resolve('examples/simple.json')));
q('#close-compare').click();
q('#open-local-file').click();
await until(()=>q('#local-file-list button'),'File listing');
q('#local-file-path').value=resolve('examples/simple.json');
q('#local-file-open').click();
await until(()=>state.projectPath===resolve('examples/simple.json') && !q('#local-file-dialog').open,'Full path opening');
assert(state.projectAttached);
const currentSource=state.source;
q('#open-compare').click();
assert(q('#compare-dialog').open);
q('#compare-history').click();
await until(()=>q('#compare-revisions').options.length,'History listing');
const option=q('#compare-revisions').options[0];
assert.match(option.value,/^[a-f0-9]{40,64}$/);
assert(option.textContent.includes(option.value.slice(0,8)));
assert.match(option.textContent,/\d{4}-\d{2}-\d{2}/);
q('#compare-revisions').value=option.value;
q('#compare-revisions').dispatchEvent(new window.Event('change'));
await until(()=>q('#compare-status').textContent.startsWith('Baseline:'),'Revision load');
assert.equal(state.source,currentSource,'History must not replace unsaved editor');
assert(q('#compare-mode-toggle').checked);
const baseline={title:'Baseline budget',tasks:[{name:'Work',id:'work',start:'2026-01-01',end:'2026-04-01',cost:100}]};
const actual={...baseline,title:'Current budget',tasks:[{...baseline.tasks[0],end:'2026-06-01',cost:150}]};
q('#source').value=JSON.stringify(actual);q('#source').dispatchEvent(new window.Event('input'));
Object.defineProperty(q('#compare-file'),'files',{configurable:true,value:[{name:'independent.json',text:async()=>JSON.stringify(baseline)}]});
q('#compare-file').dispatchEvent(new window.Event('change'));
await until(()=>q('#compare-status').textContent.includes('independent.json'),'Uploaded independent baseline');
assert.equal(q('#confirm-compare').disabled,false);
q('#confirm-compare').click();
assert.equal(q('#compare-dialog').open,false,'Apply comparison must close the picker window');
const {exportChart}=await import('../jsonantt/web/export.mjs');
for(const mode of ['gantt','table','burn','burndown','burnup','burn-table']) {
  q(`[data-canvas-tab="${mode}"]`).click();
  await until(()=>q('#canvas > svg')?.dataset.previewMode===`compare-${mode}` && q('#canvas').getAttribute('aria-busy')!=='true','Compare '+mode);
  assert.equal(q('#canvas img'),null);
  assert.equal(state.source,JSON.stringify(actual));
  const blob=await exportChart(JSON.stringify({planned:baseline,actual}),{mode:`compare-${mode}`,format:'png',dpi:40});
  assert.equal(blob.type,'image/png');assert(blob.size>100);
  if(mode.endsWith('table')) {
    const csv=await exportChart(JSON.stringify({planned:baseline,actual}),{mode:`compare-${mode}`,format:'csv'});
    assert((await csv.text()).includes('Work'));
  }
}
q('#compare-mode-toggle').checked=false;q('#compare-mode-toggle').dispatchEvent(new window.Event('change'));
await until(()=>q('#canvas > svg')?.dataset.previewMode==='burn-table','Comparison off');
assert(q('#compare-indicator').hidden);
console.log('Passed File comparison dialog, full-path local picker, dated Git revisions, independent upload, all six compared previews/PNG exports, table CSVs and mode toggle.');
dom.window.close();
