import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(resolve(process.argv[2],'package.json'));
const {JSDOM}=require('jsdom');
const dom=new JSDOM('<dialog open><div id="settings"></div></dialog>',{url:'http://localhost/',pretendToBeVisual:true});
for(const key of ['window','document','HTMLElement']) globalThis[key]=dom.window[key];
HTMLElement.prototype.showPopover=function(){this.dataset.topLayer='true';};
const {renderChartSettings}=await import('../jsonantt/web/settings.mjs');
const {attachDatePicker}=await import('../jsonantt/web/datepicker.mjs');
const source={dateformat:'%d/%m/%Y',start:'01/06/2026',end:'30/06/2026',style:{fiscal_year_start:'10'}};
renderChartSettings(document.querySelector('#settings'),source,{onCommit(){}});
for(const key of ['start','end','fiscal_year_start']) {
  const input=document.querySelector(`[data-setting="${key}"]`);
  const trigger=input.closest('.date-field').querySelector('button');
  assert(trigger);
  trigger.click();
  const popup=document.querySelector('.date-picker');
  assert.equal(popup.parentElement.tagName,'DIALOG','Calendar must stay in modal focus scope');
  assert.equal(popup.dataset.topLayer,'true','Calendar must escape modal clipping');
  assert.equal(trigger.getAttribute('aria-expanded'),'true');
  [...popup.querySelectorAll('.date-picker-day')].find(button=>button.textContent==='15').click();
  assert.equal(document.querySelector('.date-picker'),null);
  assert.equal(trigger.getAttribute('aria-expanded'),'false');
  assert.equal(key==='fiscal_year_start'?source.style[key]:source[key],key==='fiscal_year_start'?'10-15':'15/06/2026');
}
const input=document.createElement('input');
input.value='01/06/2026, 10/07/2026';
let picked;
document.body.append(attachDatePicker(input,{format:'%d/%m/%Y',multiple:true,onPick:value=>picked=value}));
input.closest('.date-field').querySelector('button').click();
assert(document.querySelector('.date-picker-header strong').textContent.includes('July'));
[...document.querySelectorAll('.date-picker-day')].find(button=>button.textContent==='20').click();
assert.equal(picked,'01/06/2026, 20/07/2026');
input.closest('.date-field').querySelector('button').click();
document.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));
assert.equal(document.querySelector('.date-picker'),null);
assert(document.querySelector('dialog').hasAttribute('open'));
console.log('Passed date settings, fiscal picker, modal top-layer placement, milestone chain preservation and Escape.');
