// Build the site with --prerender, then pass its path and a jsdom/fake-indexeddb package directory.
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(resolve(process.argv[3],'package.json'));
const {JSDOM}=require('jsdom');
const {indexedDB}=require('fake-indexeddb');
const site=process.argv[2];
const html=readFileSync(resolve(site,'index.html'),'utf8');
const bundle=JSON.parse(readFileSync(resolve(site,'startup-previews.json'),'utf8'));
const dom=new JSDOM(html,{url:'https://example.test/jsonantt/?demo=1',pretendToBeVisual:true});
for(const key of ['window','document','localStorage','HTMLElement','HTMLLabelElement','navigator','DOMParser']) Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
globalThis.indexedDB=indexedDB;
let workers=0,requests=0;
globalThis.Worker=class {constructor(){workers++;} postMessage(){} };
globalThis.fetch=async url=>{
  assert(String(url).endsWith('/startup-previews.json'),'Startup must not probe a server or download Python: '+url);
  requests++;
  return new Response(JSON.stringify(bundle));
};
const start=performance.now();
const {state}=await import('../jsonantt/web/app.mjs');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
for(let i=0;i<200 && !document.querySelector('#canvas > svg');i++) await sleep(10);
const svg=document.querySelector('#canvas > svg');
assert(svg,'Built-in demo must appear without a Python runtime');
assert.equal(workers,0,'No Python worker may be on the critical path to the first preview');
assert.equal(requests,1,'No duplicate health probes or bundle requests');
assert(svg.querySelector('[data-key]'),'Prebuilt SVG must remain interactive');
assert.equal(svg.querySelector('image'),null);
const firstMs=performance.now()-start;
const target=svg.querySelector('[data-key]');
target.dispatchEvent(new window.MouseEvent('click',{bubbles:true}));
assert.equal(state.selection.key,target.dataset.key);
const {createPreviewStore,previewKey}=await import('../jsonantt/web/preview-store.mjs');
const {createPreviewLoader}=await import('../jsonantt/web/preview.mjs');
const original=JSON.parse(bundle.previews[0].source);
const source=JSON.stringify({...original,title:'Saved custom chart'});
const key=previewKey(source,{mode:'gantt'});
const store=createPreviewStore(bundle.version);
await store.put(key,bundle.previews[0].svg);
assert.equal(previewKey(JSON.stringify(JSON.parse(source),null,2),{mode:'gantt',renderDepth:0,tableFilter:'tasks'}),key);
// A fresh loader/store models a reload: no in-memory SVG cache survives.
let restored,errors=[];
const loader=createPreviewLoader({store:createPreviewStore(bundle.version),useBrowser:()=>true,
  onRender:view=>{restored=view;},onError:error=>errors.push(error)});
const refreshStart=performance.now();
loader.schedule(source,state.chart,{mode:'gantt'},null);
for(let i=0;i<100 && !restored;i++) await sleep(5);
assert(restored,'Saved custom preview must restore without starting Python');
assert.equal(workers,0);
assert.deepEqual(errors,[]);
const refreshMs=performance.now()-refreshStart;
assert.equal(await createPreviewStore('different-build').get(key),null,'New renderer build invalidates cache');
assert.equal(await createPreviewStore(bundle.version).get(previewKey(source,{mode:'gantt',renderDepth:1})),null,'Different rollup depth must miss');
const bundledKey=previewKey(bundle.previews[0].source,bundle.previews[0].options);
globalThis.indexedDB=undefined;
assert(await createPreviewStore(bundle.version).get(bundledKey),'Blocked storage must still allow bundled previews');
globalThis.indexedDB=indexedDB;
loader.cancel();
await sleep(520);
assert.equal(workers,1,'Warm Python only after the initial preview is visible');
console.log('Passed instant interactive demo, persisted custom refresh, background warmup and cache invalidation.');
console.log(JSON.stringify({firstPreviewMs:Math.round(firstMs),refreshPreviewMs:Math.round(refreshMs),pythonRequiredBeforePreview:false}));
