import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(resolve(process.argv[2],'package.json'));
const {JSDOM}=require('jsdom');
const dom=new JSDOM('<button id="theme" role="switch"><small data-theme-label></small></button>',{url:'http://localhost/'});
for(const key of ['window','document','localStorage'])globalThis[key]=dom.window[key];
let changed;
const media={matches:true,addEventListener(type,fn){changed=fn;}};
window.matchMedia=()=>media;
const {wireThemeControl}=await import('../jsonantt/web/theme.mjs');
const control=document.querySelector('button');
wireThemeControl(control);
assert.equal(control.getAttribute('aria-checked'),'true');
assert.equal(control.textContent,'Dark');
assert.equal(document.documentElement.dataset.theme,'dark');
media.matches=false;changed();
assert.equal(document.documentElement.dataset.theme,'light');
assert.equal(control.getAttribute('aria-checked'),'false');
assert.equal(control.textContent,'Light');
control.click();
changed();assert.equal(document.documentElement.dataset.theme,'dark');
assert.equal(localStorage.getItem('jsonantt.theme'),'dark');
control.click();
assert.equal(document.documentElement.dataset.theme,'light');
media.matches=true;changed();assert.equal(document.documentElement.dataset.theme,'light');
assert.equal(localStorage.getItem('jsonantt.theme'),'light');
const restored=document.createElement('button');
wireThemeControl(restored);
assert.equal(restored.getAttribute('aria-checked'),'false','Saved manual preference survives a new launch');
localStorage.removeItem('jsonantt.theme');
wireThemeControl(document.createElement('button'));
assert.equal(document.documentElement.dataset.theme,'dark','No saved choice starts from system');
console.log('Passed two-state toggle, OS-selected default, live system following before override, and remembered manual choice.');
